### ISSUE TITLE
Pasting text while renaming file/folder is not working as expected

### ISSUE THREAD

**Issue by alex21311** [droppyjs/droppy#17]
## Problem
If I start to rename a file or folder, the paste-command (ctrl+v) cancels the renaming and creates a new textfile with the pasted text.

## Solution
If renaming of a file or folder is in progress, pasting a text should add it to the file/folder name.

**Comment by markhughes** [comment]
This should be a fairly simple one to fix up, thanks!

**Comment by markhughes** [comment]
Resolved in #17

**Comment by alex21311** [comment]
Sorry, but issue is not solved:
![BUPAnKwKz4](https://user-images.githubusercontent.com/82875421/117178714-a3562000-add2-11eb-8f3e-ec6763785153.gif)

**Comment by markhughes** [comment]
@alex21311 can you try deleting your droppy cache directory? I will need to set this up to do it for you automatically in the future.

**Comment by alex21311** [comment]
I'm running droppy inside a docker container and I would expect the cache is dropped when the container is recreated with the new image

**Comment by markhughes** [comment]
I will investigate this further for you.

**Comment by markhughes** [comment]
There is now a cache clear added to resolve this, and you should see it when we release 0.0.6.

**Comment by markhughes** [comment]
0.0.6 has been published. Thanks!
